name: grit-benchmark
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python
- conda-forge::pandas
- conda-forge::numpy
- conda-forge::pathlib
- conda-forge::requests
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::widgetsnbextension
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::matplotlib
- conda-forge::plotnine
- conda-forge::seaborn
- conda-forge::umap-learn
- conda-forge::black
- conda-forge::nb_black
- bioconda::mygene=3.1.0
- pip:
  - s_gd2==1.5
  - phate==1.0.4
  - dvc==2.36.0
  - dvc-s3==2.21.0
  - git+https://github.com/cytomining/pycytominer@afac3ea16818ad25f37318ecd5c5090c0eff5806
  - cytominer-eval==0.1
